# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170921_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='courses.Course'),
            preserve_default=False,
        ),
    ]
