# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170921_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='courses.Course'),
        ),
    ]
